language: python

matrix:
    include:
        - python: 3.6
        - python: 3.7
          dist: xenial
          sudo: required

install:
    - cd $TRAVIS_BUILD_DIR
    - pip install -U . -r requirements-test.txt

script:
    - mypy tractor/  --ignore-missing-imports
    - pytest tests/ --no-print-logs
